### ISSUE TITLE
CUDA out of memory issue

### ISSUE THREAD

**Issue by 0xinit** [rbbrdckybk/ai-art-generator#3]
Hi, 

I ran the first test successfully with the lighthouse prompt. It works great! But for the second time, I ran into this issue: 

RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 23.69 GiB total capacity; 20.71 GiB already allocated; 187.50 MiB free; 20.78 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I dont understand why, because when I do nvidia-smi, it shows that I have enough space. I have ran torch.cuda.empty_cache as well, but it doesnt seem to work. 

Any help would be appreciated. Thanks, and great work!

**Comment by scotig33** [comment]
any fixes? Getting the same error.

**Comment by heyitshestia** [comment]
I reduced the resolution and it work. Only working with 8GB tho so i don't know at what resolution you're trying to make the images. But with 20 gigs i'd say you could go 1080x900? Maybe?

**Comment by 0xinit** [comment]
@heyitshestia @scotig33 I tried with my 24gb 3090 GPU, and it doesn't work with 1080x900 as far as i remember. I think the lowest I tried was 720x720 and it worked fine.

**Comment by heyitshestia** [comment]
720 what a dream, highest i can do is 384x384. I guess going any higher means a new GPU right? Seeing as you can't generate images in smaller chunks or anything.

**Comment by 0xinit** [comment]
Not sure what you mean by generating in smaller chunks, but yeah you'd need a high ram in your GPU
